### ISSUE TITLE
Add types package

### ISSUE THREAD

**Issue by dmazaleuskaya** [erzki/signalr-asp-net#1]
You mentioned in the description that there is a matching types package, however it doesn't exits in the registry. Could you please add the types package?

**Comment by gregveres** [comment]
@erzki Was this an oversight or are you missing the types package and it needs to be built?

**Comment by erzki** [comment]
I missed to add the types. If you can, please create a PR with the types
included.

Den fre 8 jan. 2021 01:38Greg Veres <notifications@github.com> skrev:

**Comment by erzki** [comment]
Fixed in #4 
It's also published as a new version to npm (1.0.3)
